version: '2'

services:

  # ---------------------
  # The rabbitMQ service
  # ---------------------
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_VHOST: "/"
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
      
  # ---------------------
  # The mysql service    
  # ---------------------
  mysql:
    image: "mysql:5.7"
    hostname: "mysql"
    environment:
      MYSQL_DATABASE: "hawkbit"
      MYSQL_USER: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    restart: always
    ports:
      - "3306:3306"
    labels:
      NAME: "mysql"
  
  # ---------------------
  # The hawkbit service
  # ---------------------
  hawkbit:
    image: "hawkbit/hawkbit-update-server:0.2.0M4-mysql"
    hostname: "hawkbit"
    links:
        - mysql
        - rabbitmq
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/hawkbit'
      - 'SPRING_RABBITMQ_HOST=rabbitmq'
      - 'SPRING_RABBITMQ_USERNAME=guest'
      - 'SPRING_RABBITMQ_PASSWORD=guest'
      - 'SPRING_DATASOURCE_USERNAME=root'
    restart: always
    ports:
<<<<<<< HEAD
      - "8085:8085"
=======
      - "8080:8080"
>>>>>>> c80b5b5c09c23126118b1e114cc92be86baba850
    labels:
      NAME: "hawkbit"

  # ---------------------
  # The hawkbit-simulator service
  # ---------------------
  hawkbit-simulator:
    image: "hawkbit/hawkbit-device-simulator:latest"
    hostname: "hawkbit-device-simulator"
    links:
        - hawkbit
        - rabbitmq    
    environment:
      - 'SPRING_RABBITMQ_HOST=rabbitmq'
      - 'SERVER_SESSION_COOKIE_NAME=hawkbitsimu'
    restart: always
    ports:
      - "8083:8083"
    labels:
<<<<<<< HEAD
      NAME: "hawkbit-device-simulator"
=======
      NAME: "hawkbit-device-simulator"
>>>>>>> c80b5b5c09c23126118b1e114cc92be86baba850
